/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TemplatesIndexImport } from './routes/templates/index'
import { Route as SettingsThemeImport } from './routes/settings/theme'
import { Route as SettingsGeneralImport } from './routes/settings/general'
import { Route as SettingsCustomLabImport } from './routes/settings/custom-lab'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TemplatesIndexRoute = TemplatesIndexImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsThemeRoute = SettingsThemeImport.update({
  id: '/settings/theme',
  path: '/settings/theme',
  getParentRoute: () => rootRoute,
} as any)

const SettingsGeneralRoute = SettingsGeneralImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRoute,
} as any)

const SettingsCustomLabRoute = SettingsCustomLabImport.update({
  id: '/settings/custom-lab',
  path: '/settings/custom-lab',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/custom-lab': {
      id: '/settings/custom-lab'
      path: '/settings/custom-lab'
      fullPath: '/settings/custom-lab'
      preLoaderRoute: typeof SettingsCustomLabImport
      parentRoute: typeof rootRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralImport
      parentRoute: typeof rootRoute
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/settings/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeImport
      parentRoute: typeof rootRoute
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/custom-lab': typeof SettingsCustomLabRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/templates': typeof TemplatesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/custom-lab': typeof SettingsCustomLabRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/templates': typeof TemplatesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/settings/custom-lab': typeof SettingsCustomLabRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/templates/': typeof TemplatesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings/custom-lab'
    | '/settings/general'
    | '/settings/theme'
    | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/custom-lab'
    | '/settings/general'
    | '/settings/theme'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/settings/custom-lab'
    | '/settings/general'
    | '/settings/theme'
    | '/templates/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsCustomLabRoute: typeof SettingsCustomLabRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsCustomLabRoute: SettingsCustomLabRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/settings/custom-lab",
        "/settings/general",
        "/settings/theme",
        "/templates/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/settings/custom-lab": {
      "filePath": "settings/custom-lab.tsx"
    },
    "/settings/general": {
      "filePath": "settings/general.tsx"
    },
    "/settings/theme": {
      "filePath": "settings/theme.tsx"
    },
    "/templates/": {
      "filePath": "templates/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
